### ISSUE TITLE
module_factory fails with FileNotFoundError: component/message/en.json

### ISSUE THREAD

**Issue by kuonat** [12rambau/sepal_ui#424]
**Describe the bug**
I'm following the guide to create a SEPAL module (https://sepal-ui.readthedocs.io/en/latest/tutorials/create-module.html) and I have already created an empty public github repo. When I execute `module_factory` in my instance's terminal, I get the following error output (the github repo is not updated): 

Cloning into '/home/kkuonath/MyFirstModule'...
remote: Enumerating objects: 403, done.
remote: Counting objects: 100% (403/403), done.
remote: Compressing objects: 100% (263/263), done.
remote: Total 403 (delta 212), reused 282 (delta 118), pack-reused 0
Receiving objects: 100% (403/403), 372.01 KiB | 1.90 MiB/s, done.
Resolving deltas: 100% (212/212), done.
Write a default README.md file
Write a default ABOUT.md file
Update the module name in the json translation dictionaries
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sepal_ui/bin/module_factory", line 239, in <module>
    set_module_name(folder, module_name)
  File "/usr/local/lib/python3.8/dist-packages/sepal_ui/bin/module_factory", line 65, in set_module_name
    with file.open("r") as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kkuonath/MyFirstModule/component/message/en.json'

**To Reproduce**
1. Create an empty github repo
2. Follow the steps until running `module_factory` in your SEPAL terminal
3. Get an error

**Expected behavior**
Creation of a basic module and the github repo should be updated with the new content.

**Comment by 12rambau** [comment]
the sepal_ui_template is not inlined with the new structure of the `module_factory` command line since .... I think 2 weeks, I'll be moving your issue there.

In the meantime what you can do is simply use the master branch as a template.
